// Generated by gencpp from file dobot/CartesianSimple.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_CARTESIANSIMPLE_H
#define DOBOT_MESSAGE_CARTESIANSIMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct CartesianSimple_
{
  typedef CartesianSimple_<ContainerAllocator> Type;

  CartesianSimple_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)  {
    }
  CartesianSimple_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::dobot::CartesianSimple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::CartesianSimple_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianSimple_

typedef ::dobot::CartesianSimple_<std::allocator<void> > CartesianSimple;

typedef boost::shared_ptr< ::dobot::CartesianSimple > CartesianSimplePtr;
typedef boost::shared_ptr< ::dobot::CartesianSimple const> CartesianSimpleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::CartesianSimple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::CartesianSimple_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::CartesianSimple_<ContainerAllocator1> & lhs, const ::dobot::CartesianSimple_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::CartesianSimple_<ContainerAllocator1> & lhs, const ::dobot::CartesianSimple_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::CartesianSimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::CartesianSimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::CartesianSimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::CartesianSimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::CartesianSimple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::CartesianSimple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::CartesianSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc13c46bdf00e218620490fb1dd05090";
  }

  static const char* value(const ::dobot::CartesianSimple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc13c46bdf00e218ULL;
  static const uint64_t static_value2 = 0x620490fb1dd05090ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::CartesianSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/CartesianSimple";
  }

  static const char* value(const ::dobot::CartesianSimple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::CartesianSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 r\n"
;
  }

  static const char* value(const ::dobot::CartesianSimple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::CartesianSimple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianSimple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::CartesianSimple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::CartesianSimple_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_CARTESIANSIMPLE_H
